id: 686f52a33a3d4f02899a1ad3b3b3301d
initial_creation_type: TMX
origin_type: translation
source_metadata:
  id: ''
  title: Toh_558-Destroyer_of_the_Great_Trichiliocosm-v1
  language: bo
  author: ''
  volume: {}
